import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

export default defineConfig({
  site: process.env.SITE_URL || 'https://openatv.github.io',
  base: process.env.BASE_PATH || '/enigma2-doku',
  output: 'static',
  trailingSlash: 'always',
  integrations: [starlight({
    title: { de: 'OpenATV Handbuch', en: 'OpenATV Handbook' },
    description: 'Enigma2 verstehen. Einstellungen finden. Schritt für Schritt einrichten.',
    logo: { src: './src/assets/openatv-logo.png', alt: 'OpenATV', replacesTitle: true },
    favicon: '/branding/openatv-icon.png',
    defaultLocale: 'de',
    locales: { de: { label: 'Deutsch', lang: 'de' }, en: { label: 'English', lang: 'en' } },
    customCss: ['./src/styles/custom.css'],
    components: {
      LanguageSelect: './src/components/LanguageSelect.astro',
      PageTitle: './src/components/TranslationPageTitle.astro',
    },
    social: [{ icon: 'github', label: 'GitHub', href: 'https://github.com/openatv/enigma2-doku' }],
    editLink: { baseUrl: 'https://github.com/openatv/enigma2-doku/edit/main/' },
    sidebar: [
      { label: 'Handbuch', translations: { en: 'Handbook' }, items: [
        { slug: '', label: 'Übersicht', translations: { en: 'Overview' } },
        { slug: 'erste-schritte/ersteinrichtung', label: 'Erste Einrichtung', translations: { en: 'First setup' } },
        { slug: 'erste-schritte/bedienung', label: 'Bedienung & Menüs', translations: { en: 'Controls & menus' } },
        { slug: 'erste-schritte/menue-anpassen', label: 'Menüoptionen & OSD', translations: { en: 'Menu options & OSD' } },
        { slug: 'erste-schritte/infobar', label: 'Infobar verstehen', translations: { en: 'Understand the Infobar' } },
        { slug: 'erste-schritte/farbtasten-langdruck', label: 'Farbtasten & Langdruck', translations: { en: 'Colour buttons & long presses' } },
      ] },
      { label: 'Einrichten', translations: { en: 'Set up' }, items: [
        { slug: 'tuner/konfiguration', label: 'Tuner & Sendersuche', translations: { en: 'Tuners & channel scan' } },
        { slug: 'netzwerk/lan', label: 'LAN & IP-Einstellungen', translations: { en: 'LAN & IP settings' } },
        { slug: 'netzwerk/wlan', label: 'WLAN verbinden', translations: { en: 'Connect Wi-Fi' } },
        { label: 'NAS & Netzwerkfreigaben', translations: { en: 'NAS & network shares' }, collapsed: true, items: [
          { slug: 'netzwerk/freigaben', label: 'Einstieg & Mountpfade', translations: { en: 'Getting started & mount paths' } },
          { slug: 'netzwerk/nfs', label: 'NFS verbinden & Optionen', translations: { en: 'Connect NFS & options' } },
          { slug: 'netzwerk/smb-cifs', label: 'SMB/CIFS zum NAS', translations: { en: 'SMB/CIFS to a NAS' } },
          { slug: 'netzwerk/windows11', label: 'Windows 11 vorbereiten', translations: { en: 'Prepare Windows 11' } },
          { slug: 'netzwerk/autofs-fstab', label: 'autofs, fstab & NAS-Ausfälle', translations: { en: 'autofs, fstab & NAS outages' } },
          { slug: 'netzwerk/nfs-server', label: 'Box als NFS-Server', translations: { en: 'Receiver as an NFS server' } },
        ] },
        { slug: 'netzwerk/fernzugriff', label: 'SSH, Dateien & Passwort', translations: { en: 'SSH, files & password' } },
        { slug: 'plugins/installieren', label: 'Plugins installieren', translations: { en: 'Install plugins' } },
        { slug: 'settings/senderlisten', label: 'Settings & Senderlisten', translations: { en: 'Settings & channel lists' } },
        { slug: 'settings/kanalliste', label: 'Kanalliste & Stile', translations: { en: 'Channel list & styles' } },
      ] },
      { label: 'EPG, Timer & Zeit', translations: { en: 'EPG, timers & time' }, items: [
        { slug: 'epg/grundlagen', label: 'EPG-Daten & Cache', translations: { en: 'EPG data & cache' } },
        { slug: 'epg/ansichten', label: 'EPG-Ansichten & Primetime', translations: { en: 'EPG views & prime time' } },
        { slug: 'epg/tasten', label: 'INFO, EPG & Langdruck', translations: { en: 'INFO, EPG & long presses' } },
        { slug: 'epg/fehlende-daten', label: 'Fehlender EPG & IPTV', translations: { en: 'Missing EPG & IPTV' } },
        { slug: 'timer/aufnahmen', label: 'Aufnahme- & Umschalttimer', translations: { en: 'Recording & zap timers' } },
        { label: 'AutoTimer', collapsed: true, items: [
          { slug: 'addons/autotimer', label: 'Suchregeln & Serien', translations: { en: 'Search rules & series' } },
          { slug: 'addons/autotimer-optionen', label: 'Alle 24 Einstellungen', translations: { en: 'All 24 settings' } },
        ] },
        { slug: 'timer/aufgaben', label: 'Aufgaben & Ausschalttimer', translations: { en: 'Tasks & sleep timers' } },
        { slug: 'timer/cron', label: 'Linux-Cron', translations: { en: 'Linux cron' } },
        { slug: 'system/zeit-aufwachen', label: 'Uhrzeit, NTP & Aufwachen', translations: { en: 'Time, NTP & wakeup' } },
      ] },
      { label: 'Aufnahmen & Dateien', translations: { en: 'Recordings & files' }, items: [
        { slug: 'aufnahmen', label: 'MovieSelection, EMC oder Dateimanager?', translations: { en: 'MovieSelection, EMC or file manager?' } },
        { slug: 'aufnahmen/movieselection', label: 'MovieSelection & Optionen', translations: { en: 'MovieSelection & options' } },
        { label: 'EnhancedMovieCenter (EMC)', collapsed: true, items: [
          { slug: 'addons/emc', label: 'Start, Tasten & Menü', translations: { en: 'Getting started, buttons & menu' } },
          { slug: 'addons/emc-bibliothek', label: 'Bibliothek, Cover & Skin', translations: { en: 'Library, covers & skin' } },
          { slug: 'addons/emc-wiedergabe', label: 'Wiedergabe & Sprachen', translations: { en: 'Playback & languages' } },
          { slug: 'addons/emc-papierkorb', label: 'Papierkorb, NAS & Automatik', translations: { en: 'Trash, NAS & automation' } },
          { slug: 'addons/emc-optionen', label: 'Alle 135 Setup-Optionen', translations: { en: 'All 135 setup options' } },
        ] },
        { slug: 'addons/filecommander', label: 'FileCommander & Optionen', translations: { en: 'FileCommander & options' } },
      ] },
      { label: 'Wiedergabe & Untertitel', translations: { en: 'Playback & subtitles' }, collapsed: true, items: [
        { slug: 'wiedergabe', label: 'Welcher Player macht was?', translations: { en: 'Which player does what?' } },
        { slug: 'wiedergabe/mediaplayer', label: 'MediaPlayer & Playlists', translations: { en: 'MediaPlayer & playlists' } },
        { slug: 'wiedergabe/dvd-bluray', label: 'DVD & Blu-ray', translations: { en: 'DVD & Blu-ray' } },
        { slug: 'wiedergabe/serviceapp', label: 'ServiceApp, gstplayer & exteplayer3', translations: { en: 'ServiceApp, gstplayer & exteplayer3' } },
        { slug: 'wiedergabe/servicereferenzen', label: 'Servicereferenzen & IPTV', translations: { en: 'Service references & IPTV' } },
        { slug: 'wiedergabe/untertitel', label: 'Untertitel & Sprachen', translations: { en: 'Subtitles & languages' } },
        { slug: 'wiedergabe/subssupport', label: 'SubsSupport', translations: { en: 'SubsSupport' } },
        { slug: 'wiedergabe/teletext', label: 'Teletext & Optionen', translations: { en: 'Teletext & options' } },
        { slug: 'wiedergabe/formate', label: 'Formate, Codecs & Fehlersuche', translations: { en: 'Formats, codecs & troubleshooting' } },
      ] },
      { label: 'e2MDB ab OpenATV 8.0', translations: { en: 'e2MDB for OpenATV 8.0+' }, collapsed: true, items: [
        { slug: 'addons/e2mdb', label: 'Übersicht & Lesepfade', translations: { en: 'Overview & reading paths' } },
        { slug: 'addons/e2mdb/einrichtung', label: 'Einrichtung', translations: { en: 'First setup' } },
        { slug: 'addons/e2mdb/optionen', label: 'Alle 47 Einstellungen', translations: { en: 'All 47 settings' } },
        { slug: 'addons/e2mdb/api-schluessel', label: 'API-Schlüssel', translations: { en: 'API keys' } },
        { slug: 'addons/e2mdb/anbieter-sprache', label: 'Anbieter & Sprache', translations: { en: 'Providers & language' } },
        { slug: 'addons/e2mdb/medienpfade', label: 'Medienpfade & Scan', translations: { en: 'Media paths & scanning' } },
        { slug: 'addons/e2mdb/treffer-korrigieren', label: 'Treffer korrigieren', translations: { en: 'Correct matches' } },
        { slug: 'addons/e2mdb/vorbefuellung', label: 'Live/EPG & Vorbefüllung', translations: { en: 'Live/EPG & prefill' } },
        { slug: 'addons/e2mdb/aufgabenplanung', label: 'Aufgabenplanung', translations: { en: 'Scheduled tasks' } },
        { slug: 'addons/e2mdb/senderliste', label: 'Bilder in der Senderliste', translations: { en: 'Channel-list artwork' } },
        { slug: 'addons/e2mdb/weboberflaeche', label: 'Weboberfläche', translations: { en: 'Web interface' } },
        { slug: 'addons/e2mdb/status', label: 'Status & Wartung', translations: { en: 'Status & maintenance' } },
        { slug: 'addons/e2mdb/probleme', label: 'Fehlersuche', translations: { en: 'Troubleshooting' } },
        { slug: 'addons/e2mdb/terminal', label: 'Terminal & Sicherung', translations: { en: 'Terminal & backup' } },
        { slug: 'addons/e2mdb/skinner-grundlagen', label: 'Skinner-Anhänge', translations: { en: 'Skinner appendices' } },
        { slug: 'addons/e2mdb/converter', label: 'Converter-Referenz', translations: { en: 'Converter reference' } },
      ] },
      { label: 'Sichern & Warten', translations: { en: 'Backup & maintenance' }, items: [
        { slug: 'wartung/backup-restore', label: 'Backup & Wiederherstellung', translations: { en: 'Backup & restore' } },
        { slug: 'wartung/software-update', label: 'Softwareupdate oder neues Image?', translations: { en: 'Software update or new image?' } },
        { slug: 'wartung/flash-online', label: 'Flash Online', translations: { en: 'Flash Online' } },
        { slug: 'wartung/usb-installation', label: 'Neuinstallation per USB', translations: { en: 'USB installation' } },
        { slug: 'wartung/autorestore', label: 'AutoRestore & Add-ons', translations: { en: 'AutoRestore & add-ons' } },
        { slug: 'wartung/multiboot', label: 'MultiBoot', translations: { en: 'MultiBoot' } },
        { slug: 'speicher/laufwerke', label: 'Laufwerke & Mountpunkte', translations: { en: 'Drives & mount points' } },
        { slug: 'speicher/formatieren-pruefen', label: 'Formatieren & Prüfen', translations: { en: 'Format & check' } },
        { slug: 'speicher/nas-aufnahmen', label: 'Aufnahmen auf dem NAS', translations: { en: 'Record to a NAS' } },
        { slug: 'speicher/dateisysteme', label: 'Dateisysteme verstehen', translations: { en: 'Understand file systems' } },
      ] },
      { label: 'Nachschlagen', translations: { en: 'Reference' }, items: [
        { slug: 'einstellungen', label: 'Einstellung finden', translations: { en: 'Find a setting' } },
        { slug: 'anhaenge/langtasten', label: 'Langdruck-Verzeichnis', translations: { en: 'Long-press directory' } },
      ] },
      { label: 'Hilfe & Support', translations: { en: 'Help & support' }, items: [
        { slug: 'hilfe/probleme', label: 'Häufige Fragen', translations: { en: 'Common questions' } },
        { slug: 'hilfe/downloads-modelle', label: 'Downloads & Modelle', translations: { en: 'Downloads & models' } },
        { slug: 'hilfe/logs-diagnose', label: 'Logs aktivieren & finden', translations: { en: 'Enable & find logs' } },
        { slug: 'hilfe/fehler-melden', label: 'Fehler melden', translations: { en: 'Report a problem' } },
      ] },
      { label: 'Erweitern', translations: { en: 'Extend' }, items: [
        { slug: 'skins', label: 'Skins', translations: { en: 'Skins' } },
        { slug: 'skins/installieren', label: 'Skins vom Feed installieren', translations: { en: 'Install skins from the feed' } },
        { label: 'Umbra ab OpenATV 8.0', translations: { en: 'Umbra for OpenATV 8.0+' }, collapsed: true, items: [
          { slug: 'skins/umbra', label: 'Übersicht & Einstieg', translations: { en: 'Overview & getting started' } },
          { slug: 'skins/umbra/bedienung', label: 'Bedienung & Speichern', translations: { en: 'Controls & saving' } },
          { slug: 'skins/umbra/stilpakete', label: 'Stilpakete & Abweichungen', translations: { en: 'Style packs & overrides' } },
          { slug: 'skins/umbra/optionen', label: 'Alle 39 Stiloptionen', translations: { en: 'All 39 style options' } },
          { slug: 'skins/umbra/farben', label: 'Sieben Farbwelten', translations: { en: 'Seven palettes' } },
          { slug: 'skins/umbra/rgb', label: 'Eigene RGB-Farben', translations: { en: 'Custom RGB colours' } },
          { slug: 'skins/umbra/layout', label: 'Layout & Lesbarkeit', translations: { en: 'Layout & readability' } },
          { slug: 'skins/umbra/senderliste', label: 'Senderlistenansicht', translations: { en: 'Channel-list view' } },
          { slug: 'skins/umbra/galerie-spalten', label: 'Galerie & Spalten', translations: { en: 'Gallery & columns' } },
          { slug: 'skins/umbra/senderzeilen', label: 'Zeilen, Picons & Symbole', translations: { en: 'Rows, picons & symbols' } },
          { slug: 'skins/umbra/aufnahmen', label: 'Timer & Aufnahmefarben', translations: { en: 'Timers & recording colours' } },
          { slug: 'skins/umbra/infobar', label: 'Infobar-Layouts', translations: { en: 'Infobar layouts' } },
          { slug: 'skins/umbra/statussymbole', label: 'Infos & Statussymbole', translations: { en: 'Information & status icons' } },
          { slug: 'skins/umbra/wetter', label: 'Wetter einrichten', translations: { en: 'Configure weather' } },
          { slug: 'skins/umbra/e2mdb', label: 'Bilder mit e2MDB', translations: { en: 'Artwork with e2MDB' } },
          { slug: 'skins/umbra/plugins', label: 'Weitere Plugin-Screens', translations: { en: 'Other plugin screens' } },
          { slug: 'skins/umbra/menues-infoleisten', label: 'Menüs & weitere Infoleisten', translations: { en: 'Menus & more Infobar views' } },
          { slug: 'skins/umbra/eigene-stile', label: 'Stile speichern & übertragen', translations: { en: 'Save & transfer styles' } },
          { slug: 'skins/umbra/rezepte', label: 'Zurücksetzen & Rezepte', translations: { en: 'Reset & recipes' } },
          { slug: 'skins/umbra/aufloesung', label: 'HD, FHD & WQHD', translations: { en: 'HD, FHD & WQHD' } },
          { slug: 'skins/umbra/hilfe', label: 'Hilfe', translations: { en: 'Help' } },
          { slug: 'skins/umbra/quellen', label: 'Quellen & Bildstand', translations: { en: 'Sources & image versions' } },
        ] },
        { label: 'MetrixHD', collapsed: true, items: [
          { slug: 'skins/metrixhd', label: 'MyMetrixLite – Einstieg', translations: { en: 'MyMetrixLite – getting started' } },
          { slug: 'skins/metrixhd/aufloesung', label: 'HD, FHD & WQHD', translations: { en: 'HD, FHD & WQHD' } },
          { slug: 'skins/metrixhd/wetter', label: 'Wetter', translations: { en: 'Weather' } },
          { slug: 'skins/metrixhd/skinparts', label: 'Skinparts', translations: { en: 'Skinparts' } },
          { slug: 'skins/metrixhd/gestaltung', label: 'Schriften & Farben', translations: { en: 'Fonts & colours' } },
          { slug: 'skins/metrixhd/sonstiges', label: 'Infobar & weitere Optionen', translations: { en: 'Infobar & more options' } },
        ] },
        { slug: 'addons', label: 'Add-ons', translations: { en: 'Add-ons' } },
        { slug: 'addons/epgrefresh', label: 'EPGRefresh', translations: { en: 'EPGRefresh' } },
        { slug: 'addons/epgimport', label: 'EPGImport & Quellen', translations: { en: 'EPGImport & sources' } },
        { slug: 'anhaenge', label: 'Anhänge', translations: { en: 'Appendices' } },
      ] },
    ],
    credits: false,
    disable404Route: true,
    pagination: true,
    tableOfContents: { minHeadingLevel: 2, maxHeadingLevel: 3 },
  })],
});
