// Run the generated Pagefind search engine against local build files.
// No browser, network access or running Enigma2 instance is required.
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import assert from 'node:assert/strict';
import { normaliseBase } from './build-utils.mjs';

const root = path.resolve('dist');
const base = normaliseBase(process.env.BASE_PATH || '/enigma2-doku');
let language = 'de';
globalThis.document = {
  currentScript: null,
  querySelector: selector => selector === 'html' ? { getAttribute: key => key === 'lang' ? language : null } : null,
};
globalThis.fetch = async input => {
  const url = new URL(typeof input === 'string' ? input : input.url || input.href, 'https://search-test.invalid');
  assert.equal(url.origin, 'https://search-test.invalid');
  assert.ok(url.pathname.startsWith(`${base}/pagefind/`));
  const relative = decodeURIComponent(url.pathname.slice(base.length + 1));
  const file = path.resolve(root, relative);
  assert.ok(file.startsWith(root + path.sep));
  const body = await readFile(file);
  return new Response(body, { status: 200, headers: { 'content-type': file.endsWith('.json') ? 'application/json' : 'application/octet-stream' } });
};
const checks = [
  ...['de', 'en'].flatMap(lang => [
    [lang, 'Picon search mode', `/${lang}/bedienung/`],
    [lang, '700 ms', `/${lang}/bedienung/eingabegeraete/`],
    [lang, 'QWERTZ', `/${lang}/bedienung/tastatur/`],
    [lang, 'NTP', `/${lang}/bedienung/sprache/`],
    [lang, 'Deep Standby', `/${lang}/bedienung/display-led/`],
    [lang, 'ECM', `/${lang}/bedienung/systemanpassen/`],
    [lang, '0x100', `/${lang}/bedienung/systemanpassen/`],
    [lang, 'IR', `/${lang}/bedienung/fernbedienungscode/`],
    [lang, 'PiP', `/${lang}/bedienung/pip/`],
    [lang, 'Picon', `/${lang}/bedienung/picons/`],
    [lang, 'screenSaverMode', `/${lang}/erste-schritte/menue-anpassen/`],
    [lang, 'actionLeftRightToPageUpPageDown', `/${lang}/erste-schritte/farbtasten-langdruck/`],
    [lang, 'AutoRefresh', `/${lang}/skins/installieren/`],
    [lang, 'softcam-feed-universal', `/${lang}/entschluesselung/softcam-feed/`],
    [lang, 'AutoCam', `/${lang}/entschluesselung/softcam-autocam/`],
    [lang, 'MMI', `/${lang}/entschluesselung/ci-cam/`],
    [lang, 'storeservicepin', `/${lang}/entschluesselung/jugendschutz/`],
    [lang, 'DNSCrypt', `/${lang}/netzwerk/dns/`],
    [lang, 'SATPI', `/${lang}/netzwerk/dienste/`],
    [lang, 'smb-local.conf', `/${lang}/netzwerk/samba-server/`],
    [lang, 'CGNAT', `/${lang}/netzwerk/zusatzdienste/`],
    [lang, 'auth_for_streaming', `/${lang}/netzwerk/openwebif/optionen/`],
    [lang, 'no_root_access', `/${lang}/netzwerk/openwebif/optionen/`],
    [lang, 'XSPF', `/${lang}/netzwerk/openwebif/fernsehen-epg/`],
    [lang, 'BouquetEditor', `/${lang}/netzwerk/openwebif/werkzeuge/`],
    [lang, 'AutoTimer', `/${lang}/netzwerk/openwebif/werkzeuge/`],
    [lang, 'cert.pem', `/${lang}/netzwerk/openwebif/sicherheit/`],
    [lang, 'Shift', `/${lang}/netzwerk/openwebif/fernbedienung/`],
    [lang, '192.168.1.50', `/${lang}/netzwerk/manuelle-ip/`],
    [lang, 'nslookup', `/${lang}/netzwerk/neustart-test/`],
  ]),
  ['de', 'Toneburst', '/de/tuner/diseqc/'],
  ['de', 'AutoDiSEqC', '/de/tuner/autodiseqc/'],
  ['de', 'Quattro', '/de/tuner/lnb/'],
  ['de', 'Unicable', '/de/tuner/unicable/'],
  ['de', 'USALS', '/de/tuner/motor/'],
  ['de', 'TAR 5', '/de/tuner/hybrid-spaun/'],
  ['de', 'NIT', '/de/tuner/manueller-suchlauf/'],
  ['de', 'CableScan', '/de/tuner/cablescan/'],
  ['de', 'Blindscan', '/de/tuner/blindscan/'],
  ['de', 'FastScan', '/de/tuner/fastscan/'],
  ['de', 'PLP', '/de/tuner/single-tuner/'],
  ['de', 'AutoBouquetsMaker', '/de/tuner/autobouquetsmaker/'],
  ['de', 'RTL2832U', '/de/tuner/dabplus/'],
  ['de', 'Satfinder', '/de/tuner/signalfinder/'],
  ['en', 'Toneburst', '/en/tuner/diseqc/'],
  ['en', 'AutoDiSEqC', '/en/tuner/autodiseqc/'],
  ['en', 'Quattro', '/en/tuner/lnb/'],
  ['en', 'Unicable', '/en/tuner/unicable/'],
  ['en', 'USALS', '/en/tuner/motor/'],
  ['en', 'TAR 5', '/en/tuner/hybrid-spaun/'],
  ['en', 'NIT', '/en/tuner/manueller-suchlauf/'],
  ['en', 'CableScan', '/en/tuner/cablescan/'],
  ['en', 'Blindscan', '/en/tuner/blindscan/'],
  ['en', 'FastScan', '/en/tuner/fastscan/'],
  ['en', 'PLP', '/en/tuner/single-tuner/'],
  ['en', 'AutoBouquetsMaker', '/en/tuner/autobouquetsmaker/'],
  ['en', 'RTL2832U', '/en/tuner/dabplus/'],
  ['en', 'Satfinder', '/en/tuner/signalfinder/'],
  ['de', 'eARC', '/de/bild-ton/anschliessen/'],
  ['en', 'eARC', '/en/bild-ton/anschliessen/'],
  ['de', 'EDID', '/de/bild-ton/hdmi-hdr/'],
  ['en', 'EDID', '/en/bild-ton/hdmi-hdr/'],
  ['de', 'autores_unknownres', '/de/bild-ton/video-optionen/'],
  ['en', 'autores_unknownres', '/en/bild-ton/video-optionen/'],
  ['de', 'autoresolution', '/de/bild-ton/autoresolution/'],
  ['en', 'smart1080p', '/en/bild-ton/autoresolution/'],
  ['de', 'AC3', '/de/bild-ton/audio-optionen/'],
  ['en', 'AC3', '/en/bild-ton/audio-optionen/'],
  ['de', 'TrueHD', '/de/bild-ton/audio-grundlagen/'],
  ['en', 'TrueHD', '/en/bild-ton/audio-grundlagen/'],
  ['de', 'audio_usecache', '/de/bild-ton/tonspuren/'],
  ['en', 'audio_usecache', '/en/bild-ton/tonspuren/'],
  ['de', '/etc/enigma2/volume.xml', '/de/bild-ton/lautstaerke/'],
  ['en', '/etc/enigma2/volume.xml', '/en/bild-ton/lautstaerke/'],
  ['de', 'Lipsync', '/de/bild-ton/lipsync/'],
  ['en', 'lip sync', '/en/bild-ton/lipsync/'],
  ['de', 'volume_forwarding', '/de/bild-ton/cec-optionen/'],
  ['en', 'volume_forwarding', '/en/bild-ton/cec-optionen/'],
  ['de', 'Enigma2-hdmicec', '/de/bild-ton/cec-logs/'],
  ['en', 'Enigma2-hdmicec', '/en/bild-ton/cec-logs/'],
  ['de', 'Overscan', '/de/bild-ton/bildanpassung/'],
  ['en', 'overscan', '/en/bild-ton/bildanpassung/'],
  ['de', 'Mediendatenbank', '/de/addons/e2mdb/'],
  ['en', 'adapted skin', '/en/addons/e2mdb/'],
  ['de', 'enigma2-plugin-skins-umbra', '/de/skins/installieren/'],
  ['de', 'Umbra Cinema', '/de/skins/umbra/stilpakete/'],
  ['de', 'Farbwelt', '/de/skins/umbra/farben/'],
  ['de', 'color_recording', '/de/skins/umbra/optionen/'],
  ['de', 'recordIndicatorMode', '/de/skins/umbra/optionen/'],
  ['de', 'weatherCoordinates', '/de/skins/umbra/optionen/'],
  ['de', '9.99302', '/de/skins/umbra/wetter/'],
  ['de', 'InfoBarLite', '/de/skins/umbra/menues-infoleisten/'],
  ['de', '/etc/enigma2/umbra/styles', '/de/skins/umbra/eigene-stile/'],
  ['de', 'WQHD', '/de/skins/umbra/aufloesung/'],
  ['de', 'ImageOrPicon1', '/de/addons/e2mdb/skinner-grundlagen/'],
  ['de', 'MyBase_InfoBar', '/de/addons/e2mdb/skinner-panels/'],
  ['en', 'enigma2-plugin-skins-umbra', '/en/skins/installieren/'],
  ['en', 'Umbra Cinema', '/en/skins/umbra/stilpakete/'],
  ['en', 'palette', '/en/skins/umbra/farben/'],
  ['en', 'color_recording', '/en/skins/umbra/optionen/'],
  ['en', 'recordIndicatorMode', '/en/skins/umbra/optionen/'],
  ['en', 'weatherCoordinates', '/en/skins/umbra/optionen/'],
  ['en', '9.99302', '/en/skins/umbra/wetter/'],
  ['en', 'InfoBarLite', '/en/skins/umbra/menues-infoleisten/'],
  ['en', '/etc/enigma2/umbra/styles', '/en/skins/umbra/eigene-stile/'],
  ['en', 'WQHD', '/en/skins/umbra/aufloesung/'],
  ['en', 'ImageOrPicon1', '/en/addons/e2mdb/skinner-grundlagen/'],
  ['en', 'MyBase_InfoBar', '/en/addons/e2mdb/skinner-panels/'],
  ['de', 'e2MDB', '/de/addons/e2mdb/einrichtung/'],
  ['de', 'tmdbapikey', '/de/addons/e2mdb/optionen/'],
  ['de', 'epgPrefillMaxEventsPerService', '/de/addons/e2mdb/optionen/'],
  ['de', 'no_match_retry_hours', '/de/addons/e2mdb/live-epg/'],
  ['de', 'ImageOrPicon1', '/de/addons/e2mdb/skinner-listen/'],
  ['de', 'E2MDBEventInfo', '/de/addons/e2mdb/converter/'],
  ['de', 'S01E02', '/de/addons/e2mdb/dateinamen/'],
  ['de', 'results.db', '/de/addons/e2mdb/daten-sichern/'],
  ['de', '6066', '/de/addons/e2mdb/weboberflaeche/'],
  ['de', 'FanArt', '/de/addons/e2mdb/anbieter-sprache/'],
  ['en', 'e2MDB', '/en/addons/e2mdb/einrichtung/'],
  ['en', 'tmdbapikey', '/en/addons/e2mdb/optionen/'],
  ['en', 'epgPrefillMaxEventsPerService', '/en/addons/e2mdb/optionen/'],
  ['en', 'no_match_retry_hours', '/en/addons/e2mdb/live-epg/'],
  ['en', 'ImageOrPicon1', '/en/addons/e2mdb/skinner-listen/'],
  ['en', 'E2MDBEventInfo', '/en/addons/e2mdb/converter/'],
  ['en', 'S01E02', '/en/addons/e2mdb/dateinamen/'],
  ['en', 'results.db', '/en/addons/e2mdb/daten-sichern/'],
  ['en', '6066', '/en/addons/e2mdb/weboberflaeche/'],
  ['en', 'FanArt', '/en/addons/e2mdb/anbieter-sprache/'],
  ['de', 'MediaPlayer', '/de/wiedergabe/mediaplayer/'],
  ['de', 'config.mediaplayer.repeat', '/de/wiedergabe/mediaplayer/'],
  ['de', '5002', '/de/wiedergabe/servicereferenzen/'],
  ['de', 'ServiceApp', '/de/wiedergabe/serviceapp/'],
  ['de', 'lpcm_injecion', '/de/wiedergabe/serviceapp/'],
  ['de', 'VIDEO_TS', '/de/wiedergabe/dvd-bluray/'],
  ['de', 'pango_subtitles_delay', '/de/wiedergabe/untertitel/'],
  ['de', 'SubsSupport', '/de/wiedergabe/subssupport/'],
  ['de', 'MicroDVD', '/de/wiedergabe/subssupport/'],
  ['de', 'tuxtxt_TTFScreenResX', '/de/wiedergabe/teletext/'],
  ['de', 'Remuxen', '/de/wiedergabe/formate/'],
  ['en', 'MediaPlayer', '/en/wiedergabe/mediaplayer/'],
  ['en', 'config.mediaplayer.repeat', '/en/wiedergabe/mediaplayer/'],
  ['en', '5002', '/en/wiedergabe/servicereferenzen/'],
  ['en', 'ServiceApp', '/en/wiedergabe/serviceapp/'],
  ['en', 'lpcm_injecion', '/en/wiedergabe/serviceapp/'],
  ['en', 'VIDEO_TS', '/en/wiedergabe/dvd-bluray/'],
  ['en', 'pango_subtitles_delay', '/en/wiedergabe/untertitel/'],
  ['en', 'SubsSupport', '/en/wiedergabe/subssupport/'],
  ['en', 'MicroDVD', '/en/wiedergabe/subssupport/'],
  ['en', 'tuxtxt_TTFScreenResX', '/en/wiedergabe/teletext/'],
  ['en', 'Remuxing', '/en/wiedergabe/formate/'],
  ['de', 'AutoTimer', '/de/addons/autotimer/'],
  ['de', 'autotimer.xml', '/de/addons/autotimer/'],
  ['de', 'config.plugins.autotimer.unit', '/de/addons/autotimer-optionen/'],
  ['de', 'config.plugins.autotimer.check_eit_and_remove', '/de/addons/autotimer-optionen/'],
  ['en', 'AutoTimer', '/en/addons/autotimer/'],
  ['en', 'autotimer.xml', '/en/addons/autotimer/'],
  ['en', 'config.plugins.autotimer.unit', '/en/addons/autotimer-optionen/'],
  ['en', 'config.plugins.autotimer.check_eit_and_remove', '/en/addons/autotimer-optionen/'],
  ['de', 'MovieSelection', '/de/aufnahmen/movieselection/'],
  ['de', 'EMC', '/de/addons/emc/'],
  ['de', 'config.EMC.movie_finished_clean', '/de/addons/emc-optionen/'],
  ['de', 'config.EMC.movie_preview_delay', '/de/addons/emc-optionen/'],
  ['de', 'FileCommander', '/de/addons/filecommander/'],
  ['de', 'MiniTV', '/de/addons/emc-wiedergabe/'],
  ['de', 'emc-noscan.cfg', '/de/addons/emc-papierkorb/'],
  ['en', 'MovieSelection', '/en/aufnahmen/movieselection/'],
  ['en', 'EMC', '/en/addons/emc/'],
  ['en', 'config.EMC.movie_finished_clean', '/en/addons/emc-optionen/'],
  ['en', 'config.EMC.movie_preview_delay', '/en/addons/emc-optionen/'],
  ['en', 'FileCommander', '/en/addons/filecommander/'],
  ['en', 'MiniTV', '/en/addons/emc-wiedergabe/'],
  ['en', 'emc-noscan.cfg', '/en/addons/emc-papierkorb/'],
  ['de', 'Primetime', '/de/epg/ansichten/'],
  ['en', 'prime time', '/en/epg/ansichten/'],
  ['de', 'INFO lang', '/de/epg/tasten/'],
  ['en', 'long INFO', '/en/epg/tasten/'],
  ['de', 'tvg-id', '/de/epg/fehlende-daten/'],
  ['en', 'tvg-id', '/en/epg/fehlende-daten/'],
  ['de', 'custom.channels.xml', '/de/epg/fehlende-daten/'],
  ['en', 'custom.channels.xml', '/en/epg/fehlende-daten/'],
  ['de', 'EPGRefresh', '/de/addons/epgrefresh/'],
  ['en', 'EPGRefresh', '/en/addons/epgrefresh/'],
  ['de', 'epgimport.log', '/de/addons/epgimport/'],
  ['en', 'epgimport.log', '/en/addons/epgimport/'],
  ['de', 'Umschalttimer', '/de/timer/aufnahmen/'],
  ['en', 'zap timer', '/en/timer/aufnahmen/'],
  ['de', 'scheduler.xml', '/de/timer/aufgaben/'],
  ['en', 'scheduler.xml', '/en/timer/aufgaben/'],
  ['de', 'crontab', '/de/timer/cron/'],
  ['en', 'crontab', '/en/timer/cron/'],
  ['de', 'Uhrendrift', '/de/system/zeit-aufwachen/'],
  ['en', 'clock drift', '/en/system/zeit-aufwachen/'],
  ['de', 'NTP', '/de/system/zeit-aufwachen/'],
  ['en', 'NTP', '/en/system/zeit-aufwachen/'],
  ['de', 'NFSv4', '/de/netzwerk/nfs/'],
  ['en', 'NFSv4', '/en/netzwerk/nfs/'],
  ['de', 'ntlmsspi', '/de/netzwerk/smb-cifs/'],
  ['en', 'ntlmsspi', '/en/netzwerk/smb-cifs/'],
  ['de', 'Windows 11', '/de/netzwerk/windows11/'],
  ['en', 'Windows 11', '/en/netzwerk/windows11/'],
  ['de', 'Privates Netzwerk', '/de/netzwerk/windows11/'],
  ['en', 'Private network', '/en/netzwerk/windows11/'],
  ['de', 'Spinner', '/de/netzwerk/autofs-fstab/'],
  ['en', 'spinner', '/en/netzwerk/autofs-fstab/'],
  ['de', 'root_squash', '/de/netzwerk/nfs-server/'],
  ['en', 'root_squash', '/en/netzwerk/nfs-server/'],
  ['de', 'Timeraufnahmeverzeichnis', '/de/speicher/nas-aufnahmen/'],
  ['en', 'Timer recording location', '/en/speicher/nas-aufnahmen/'],
  ['de', 'exFAT', '/de/speicher/dateisysteme/'],
  ['en', 'exFAT', '/en/speicher/dateisysteme/'],
  ['de', 'FAT32', '/de/wartung/usb-installation/'],
  ['en', 'FAT32', '/en/wartung/usb-installation/'],
  ['de', 'AutoRestore', '/de/wartung/autorestore/'],
  ['en', 'AutoRestore', '/en/wartung/autorestore/'],
  ['de', 'Softwareupdate', '/de/wartung/software-update/'],
  ['en', 'software update', '/en/wartung/software-update/'],
  ['de', 'SFTP', '/de/netzwerk/fernzugriff/'],
  ['en', 'root password', '/en/netzwerk/fernzugriff/'],
  ['de', 'FastRestore.log', '/de/hilfe/logs-diagnose/'],
  ['en', 'FastRestore.log', '/en/hilfe/logs-diagnose/'],
  ['de', 'config.crash.debugLevel', '/de/hilfe/logs-diagnose/'],
  ['en', 'config.crash.debugLevel', '/en/hilfe/logs-diagnose/'],
  ['de', 'Fehlerbericht', '/de/hilfe/fehler-melden/'],
  ['en', 'bug report', '/en/hilfe/fehler-melden/'],
  ['de', 'Modelle', '/de/hilfe/downloads-modelle/'],
  ['en', 'supported models', '/en/hilfe/downloads-modelle/'],
  ['de', 'Blau lang', '/de/erste-schritte/farbtasten-langdruck/'],
  ['en', 'long Blue', '/en/erste-schritte/farbtasten-langdruck/'],
  ['de', 'displayHelpLong', '/de/anhaenge/langtasten/'],
  ['en', 'power_long', '/en/anhaenge/langtasten/'],
  ['de', 'Wiederherstellung', '/de/wartung/backup-restore/'],
  ['en', 'settings backup', '/en/wartung/backup-restore/'],
  ['de', 'Zielslot', '/de/wartung/flash-online/'],
  ['en', 'target slot', '/en/wartung/flash-online/'],
  ['de', 'MultiBoot', '/de/wartung/multiboot/'],
  ['en', 'MultiBoot', '/en/wartung/multiboot/'],
  ['de', 'Einhängepunkt', '/de/speicher/laufwerke/'],
  ['en', 'mount point', '/en/speicher/laufwerke/'],
  ['de', 'Dateisystem prüfen', '/de/speicher/formatieren-pruefen/'],
  ['en', 'filesystem check', '/en/speicher/formatieren-pruefen/'],
  ['de', 'NAS', '/de/netzwerk/freigaben/'],
  ['de', 'mounten', '/de/netzwerk/freigaben/'],
  ['de', 'config.epg.saveepg', '/de/einstellungen/referenz/epg/'],
  ['de', 'DHCP', '/de/netzwerk/lan/'],
  ['en', 'network share', '/en/netzwerk/freigaben/'],
  ['en', 'config.epg.saveepg', '/en/einstellungen/referenz/epg/'],
  ['en', 'skin', '/en/skins/'],
  ['de', 'WQHD', '/de/skins/metrixhd/aufloesung/'],
  ['de', 'Skinparts', '/de/skins/metrixhd/skinparts/'],
  ['de', 'Kanalliste', '/de/settings/kanalliste/'],
  ['en', 'WQHD', '/en/skins/metrixhd/aufloesung/'],
  ['en', 'Skinparts', '/en/skins/metrixhd/skinparts/'],
  ['en', 'Picture grid', '/en/settings/kanalliste/'],
  ['de', 'Einfache Infoleiste', '/de/erste-schritte/infobar/'],
  ['de', 'Zweite Infoleiste', '/de/erste-schritte/infobar/'],
  ['de', 'Versteckte Menüoptionen', '/de/erste-schritte/menue-anpassen/'],
  ['de', 'horizontal', '/de/erste-schritte/menue-anpassen/'],
  ['en', 'Simple Infobar', '/en/erste-schritte/infobar/'],
  ['en', 'Second Infobar', '/en/erste-schritte/infobar/'],
  ['en', 'Hidden menu options', '/en/erste-schritte/menue-anpassen/'],
  ['en', 'horizontal', '/en/erste-schritte/menue-anpassen/'],
];
for (const lang of ['de', 'en']) {
  language = lang;
  // Each language page loads a fresh runtime in the browser. Isolate the
  // language-specific WASM stemmer here too, instead of reusing the DE runtime.
  const pagefind = await import(`${pathToFileURL(path.join(root, 'pagefind/pagefind.js')).href}?language=${lang}`);
  const instance = pagefind.createInstance({ basePath: `${base}/pagefind/`, baseUrl: `${base}/` });
  await instance.init();
  for (const [, query, expected] of checks.filter(check => check[0] === lang)) {
    const result = await instance.search(query);
    const documents = await Promise.all(result.results.slice(0, 30).map(hit => hit.data()));
    assert.ok(documents.some(document => document.url.includes(expected)), `${lang} search "${query}" did not return ${expected}`);
    assert.ok(documents.every(document => document.url.includes(`/${lang}/`)), `${lang} search leaked another language`);
    console.log(`Search OK: ${lang} "${query}"`);
  }
  await instance.destroy();
}
